version: '3'

services:
    # Frontend
    mediasoupFrontend:
        image: ysf465639310/mediasoup-demo-cloud:v2
        ports:
            - 9443:9443
            - 3000:3000
            
        working_dir: /mediasoup/public
        
        privileged: true
        
        volumes:
            - /etc/localtime:/etc/localtime
            - ../../config/config.js:/mediasoup/config/config.js:rw
            - ../../config/config.js:/mediasoup/server/config.js:rw
            - ../../config/nginx.conf:/etc/nginx/nginx.conf:rw
            - ../nginx:/run/nginx
            
        env_file:
            - ./media.env
        
        command: ["nginx","-c", "/etc/nginx/nginx.conf", "-g", "daemon off;"]
        
        
        networks:
             cloud_conference:
                ipv4_address: 172.88.0.2
                
    # mediasoup-worker
    mediasoup:
        image: ysf465639310/mediasoup-demo-cloud:v2
        ports:
            - '${PROTOO_LISTEN_PORT}:${PROTOO_LISTEN_PORT}'
            - '${MEDIASOUP_MIN_PORT}-${MEDIASOUP_MAX_PORT}:${MEDIASOUP_MIN_PORT}-${MEDIASOUP_MAX_PORT}/udp'
            - '${MEDIASOUP_MIN_PORT}-${MEDIASOUP_MAX_PORT}:${MEDIASOUP_MIN_PORT}-${MEDIASOUP_MAX_PORT}/tcp'
        working_dir: /mediasoup/server/
        
        #if you want your own config,you can use volume lis this
        volumes:
          - /etc/localtime:/etc/localtime
          - ../../config/config.js:/mediasoup/config/config.js:rw
          - ../../config/config.js:/mediasoup/server/config.js:rw
              # - ../data:/data
              #- ../storage:/storage
            
        env_file:
            - ./media.env
        
        command:  ["node", "./server.js"]
        #command: ["sleep", "10000000"]
        
        networks:
             cloud_conference:
                ipv4_address: 172.88.0.3
networks:
   cloud_conference:
      ipam:
         config:
         - subnet: 172.88.0.0/16
           #gateway: 172.88.0.1

